#!/usr/bin/env zsh

#createdb -h localhost -p 54391 -U macrostrat_admin naukluft

pg_dump -Fc \
  --no-privileges --no-owner -C -h localhost -U Daven \
  --exclude-schema=raster \
  --exclude-schema=contour \
  --exclude-schema=tiger \
  --exclude-schema=tiger_data \
  Naukluft \
> /tmp/naukluft-data-export.sql

scp /tmp/naukluft-data-export.sql gunnison:/tmp/naukluft-data-export.sql

#ssh gunnison "pg_restore -h dev.macrostrat.org -p 5432 -U macrostrat_admin -d naukluft /tmp/naukluft-data-export.sql"
