#!/usr/bin/env node -r esm
const {readFileSync, writeFileSync} = require('fs')
const {sync: mkdirp} = require('mkdirp')
const {join, resolve} = require('path')

const pgp = require('pg-promise')();
const db = pgp('postgresql:///Naukluft');

const queries = require("../build/query-spec.json");
const queryDir = resolve(__dirname, '..', 'dist-web', 'queries');
mkdirp(queryDir)

const run = async function() {
  for (const query of queries) {
    console.log(query.fileName)
    const sql = readFileSync(query.fileName, 'utf-8');
    const data = await db.query(sql, query.values)
    const fn = join(queryDir, query.outputFile)
    writeFileSync(fn, JSON.stringify(data))
  }
}

run()
  .then(()=> process.exit(0))
  .catch(e => {
    console.error(e)
    process.exit(1)
  })
